# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 04cd48ffdeb4942476806c00137dfbd32433c453043af9a66a6e713f086d3f4fdd9660b2d72596c7318603b98c90e2bd4c5d67965a61eb663d7bedbeb64ea48c

test:
  secret_key_base: 33943f7d13279bebbaae1b307a7f8b2a6be8e1a8c1563eb9a48b087f7fb12bfbcf79160c81856ba11d0aba3825701ee22263715482db0f0f9287c322831a333e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
